# Generated by Django 5.0.4 on 2024-04-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0002_section_num_class_in_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=15),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('9:30 - 10:20', '9:30 - 10:20'), ('10:20 - 11:10', '10:20 - 11:10'), ('11:10 - 12:00', '11:10 - 12:00'), ('12:00 - 12:50', '12:00 - 12:50'), ('2:00 - 2:50', '2:00 - 2:50'), ('2:50 - 3:40', '2:50 - 3:40'), ('3:40 - 4:30', '3:40 - 4:30')], default='11:30 - 12:30', max_length=50),
        ),
    ]
